baseURL = "https://somarosa.co.uk"
title = "Somarosa"
author = "somarosa.co.uk"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Google Analytics (optional)
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System (optional)
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ["blog"]
  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Tella Logo"
    size = "h-14"

  [params.site]
    name = "Tella"
    description = "Tella is a modern Hugo theme optimized for businesses, organizations, and open source projects. Fully responsive and SEO-friendly."

  [params.icon]
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Tella is a Hugo theme for modern websites, companies, and organizations. Fully respo_
